languageCode = "pt-BR"
title = "DevOps Vale"
theme = "crab"
baseurl = "https://devopsvale.surge.sh/"

[params]
mainSections = ["blog", "features"]
description = "Comunidade de DevOps do Vale do Paraíba"
logoimage = "images/logo.png"
copyright = "foo"
email = "diogo2fex@gmail.com"

# mathjax = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
## Uncomment if you want mathjax enabled. The above cdn source is taken from https://gohugo.io/content-management/formats/#mathjax-with-hugo


[permalinks]
blog  = "/blog/:year/:month/:title/"

[taxonomies]
tags = "tags"

[[menu.main]]
weight = 1
name = "Home"
url = "/"

[[menu.main]]
weight = 2
name = "Blog"
url = "/blog/"

[[menu.main]]
weight = 3
name = "Features"
identifier = "features"
  [[menu.main]]
  parent = "features"
  weight = 1
  name = "Responsive design"
  url = "/features/responsive-design/"
  [[menu.main]]
  parent = "features"
  weight = 3
  name = "Two-column layout"
  url = "/features/two-column-layout/"
  [[menu.main]]
  parent = "features"
  weight = 4
  name = "Tags"
  url = "/features/tags/"


[[menu.main]]
weight = 6
name = "Contato"
url = "/contact/"
